apiVersion: apps/v1
kind: Deployment
metadata:
  name: crr-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crr-go
  template:
    metadata:
      labels:
        app: crr-go
    spec:
      containers:
      - name: crr-go
        image: ghcr.io/iaoongin/crr-go:gh-actions-test
        imagePullPolicy: Always  # 确保每次都拉取最新的镜像
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: crr-go-data-volume
      volumes:
      - name: crr-go-data-volume
        hostPath:
          path: /data/crr-go
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: crr-go-service
spec:
  type: ClusterIP
  ports:
    - port: 30002
      targetPort: 8080
  selector:
    app: crr-go

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # I'm using ClusterIssuer here
metadata:
  name: ${CERT_MANAGER} # 证书提供者
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${EMAIL} # 邮箱
    privateKeySecretRef:
      name: ${CERT_MANAGER} # 证书提供者
    solvers:
    - http01:
        ingress:
          class: traefik

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crr-go-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: ${CERT_MANAGER} # 证书提供者
spec:
  tls:
  - hosts:
    - ${DOMAIN}  # 请替换为你的域名
  secretName: ${CERT_MANAGER} # 证书提供者
spec:
  rules:
  - host: ${DOMAIN}  # 替换为你的域名
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crr-go-service
            port:
              number: 30002
