name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # Setting an environment variable with the value of a configuration variable
  CERT_MANAGER: ${{ vars.CERT_MANAGER }}
  DOMAIN: ${{ vars.DOMAIN }}
  EMAIL: ${{ vars.EMAIL }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -v -o build/crr-go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: crr-go-${{ runner.os }}
          path: build/crr-go

  push_to_registries:
    name: Push Docker image to registries
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: crr-go-${{ runner.os }}
          path: build/crr-go
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  delpy_to_k8s:
    runs-on: ubuntu-latest
    needs: push_to_registries
    environment: default  # 指定环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Render Kubernetes YAML
      run: |
        # 安装 envsubst
        sudo apt-get install gettext-base
        # 渲染 YAML 文件
        envsubst < crr-go.yaml > rendered-crr-go.yaml

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'  # 或者指定特定版本

    - name: Configure Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Apply Kubernetes manifest
      run: |
        kubectl delete -f rendered-crr-go.yaml
        kubectl apply -f rendered-crr-go.yaml