# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Linux
        run: go build -v ./... -o dist/crr-go-linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: crr-go-linux
          path: dist/crr-go-linux
  
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build macOS
        run: go build -v ./... -o dist/crr-go-macos

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: crr-go-macos
          path: dist/crr-go-macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Windows
        run: go build -v ./... -o dist/crr-go-windows.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: crr-go-windows
          path: dist/crr-go-windows.exe
